language: python
python:
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
# command to install dependencies
install:
  - pip install requests pytest
  - python setup.py install
script:
  - photobackup run & py.test tests
